version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "terraform"
    directory: "environments/main"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "terraform"
    directory: "environments/bootstrap"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "terraform"
    directory: "environments/project-iac-repo"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    commit-message:
      prefix: "chore"
      include: "scope"
